In [1]:
## initially Lets import numpy
import numpy as np
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [2]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]
arr=np.array([my_lst1,my_lst2,my_lst3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [3]:
## check the shape of the array

arr.shape

(3, 5)

In [10]:
arr[1]

array([2, 3, 4, 5, 6])

In [12]:
arr[1:,:2]

array([[2, 3],
       [9, 7]])

In [13]:
arr[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [ ]:
### Some conditions very useful in Exploratory Data Analysis 

val=2
arr[arr<3]

array([1, 2, 2])

In [17]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
arr1=np.arange(0,10).reshape(2,5)
arr2=np.arange(0,10).reshape(2,5)
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [19]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
## random distribution
np.random.rand(3,3)

array([[0.40319494, 0.94164875, 0.75110477],
       [0.52403365, 0.62881418, 0.28157733],
       [0.78941558, 0.62182651, 0.09139821]])

In [22]:
np.random.randint(0,100,8).reshape(4,2)


array([[85, 67],
       [63, 38],
       [34, 40],
       [89, 55]], dtype=int32)

In [23]:
np.random.random_sample((1,5))

array([[0.2171759 , 0.00184595, 0.93796962, 0.27244538, 0.8302216 ]])